name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: Build with maven
      run: mvn --batch-mode --update-snapshots package

    - name: Prepare
      id: prep
      run: |
        VERSION=${GITHUB_SHA::8}
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION=${GITHUB_REF/refs\/tags\//}
        fi
        echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        echo ::set-output name=VERSION::${VERSION}

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: hellozakir/product-management
        tags: latest,v1,${{ steps.prep.outputs.VERSION }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Checkout project-management-config
      uses: actions/checkout@v3
      with:
        repository: zakirhossain-dsi/project-management-config
        path: project-management-config

    - name: Update manifests
      uses: mikefarah/yq@master
      with:
        cmd: yq -i '.spec.template.spec.containers[0].image = "docker.io/hellozakir/product-management:v2"' ./project-management-config/k8s/deployment.yaml

    - name: Print deployment
      run: cat /project-management-config/k8s/deployment.yaml


